"""post published_date field

Revision ID: 321060cc94e7
Revises: e9139f60f544
Create Date: 2022-02-18 10:59:56.573750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321060cc94e7'
down_revision = 'e9139f60f544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('publish_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'publish_date')
    # ### end Alembic commands ###
