"""post modified field

Revision ID: 697f9067239f
Revises: c60278daaa07
Create Date: 2022-01-26 14:11:01.828377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697f9067239f'
down_revision = 'c60278daaa07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'timestamp_modified')
    # ### end Alembic commands ###
