"""comment status

Revision ID: e9139f60f544
Revises: a1c081531ddc
Create Date: 2022-01-31 16:16:30.726955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9139f60f544'
down_revision = 'a1c081531ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.BOOLEAN(), nullable=True))
    op.drop_column('comments', 'status')
    # ### end Alembic commands ###
